# Generated by Django 2.1.7 on 2019-09-22 05:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Insample_start_date', models.DateField()),
                ('Insample_end_date', models.DateField()),
                ('Outsample_start_date', models.DateField()),
                ('Outsample_end_date', models.DateField()),
                ('stock', models.TextField()),
                ('feature', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=8)),
                ('answer', models.TextField()),
                ('ml_method', models.TextField()),
            ],
            options={
                'db_table': 'Block_Input',
            },
        ),
    ]
