# Generated by Django 2.2.6 on 2019-10-24 04:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=20)),
                ('Insample_start_date', models.DateField()),
                ('Insample_end_date', models.DateField()),
                ('Outsample_start_date', models.DateField()),
                ('Outsample_end_date', models.DateField()),
                ('stock', models.TextField()),
                ('feature', django.contrib.postgres.fields.jsonb.JSONField()),
                ('answer', models.TextField()),
                ('ml_method', models.TextField()),
            ],
            options={
                'db_table': 'Block_Input',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_close', models.FloatField()),
                ('code', models.TextField()),
                ('name', models.TextField()),
                ('voucher_usage_rate', models.FloatField()),
                ('utilization_usage_rate', models.FloatField()),
                ('voucher_utilization_ratio', models.FloatField()),
                ('after_market_p', models.FloatField()),
                ('score', models.FloatField()),
                ('trust_cost', models.FloatField()),
                ('trust_ratio', models.FloatField()),
                ('trust_bs', models.FloatField()),
                ('self_cost', models.FloatField()),
                ('self_ratio', models.FloatField()),
                ('self_bs', models.FloatField()),
                ('foreign_cost', models.FloatField()),
                ('foreign_ratio', models.FloatField()),
                ('foreign_bs', models.FloatField()),
                ('external_disk', models.FloatField()),
                ('inner_disk', models.FloatField()),
                ('tail_volume', models.FloatField()),
                ('volume', models.FloatField()),
                ('close', models.FloatField()),
                ('low', models.FloatField()),
                ('high', models.FloatField()),
                ('open', models.FloatField()),
            ],
            options={
                'db_table': 'Stock_Data',
            },
        ),
    ]
