# Generated by Django 2.1.7 on 2019-09-22 05:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_stock_block', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='feature',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=8), size=8),
        ),
    ]
