# Generated by Django 2.1.7 on 2019-09-24 12:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_stock_block', '0002_auto_20190922_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('code', models.TextField()),
                ('name', models.TextField()),
                ('day_close', models.FloatField()),
                ('voucher_usage_rate', models.FloatField()),
                ('utilization_usage_rate', models.FloatField()),
                ('after_market_p', models.FloatField()),
                ('score', models.FloatField()),
                ('trust_cost', models.FloatField()),
                ('trust_ratio', models.FloatField()),
                ('trust_bs', models.FloatField()),
                ('self_cost', models.FloatField()),
                ('self_ratio', models.FloatField()),
                ('self_bs', models.FloatField()),
                ('foreign_cost', models.FloatField()),
                ('foreign_ratio', models.FloatField()),
                ('foreign_bs', models.FloatField()),
                ('external_disk', models.FloatField()),
                ('inner_disk', models.FloatField()),
                ('tail_volume', models.FloatField()),
                ('volume', models.FloatField()),
                ('close', models.FloatField()),
                ('low', models.FloatField()),
                ('high', models.FloatField()),
                ('open', models.FloatField()),
            ],
            options={
                'db_table': 'Stock_Data',
            },
        ),
        migrations.AlterField(
            model_name='block',
            name='feature',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=8),
        ),
    ]
